locale: "en-US"
title: "SATANIC DEVIL"
email: "drsamael@zohomail.cn"
description: "Modified Fairytale of A Mythical Fallen"
url: "https://drsatanic.github.io"
baseurl: "/"
repository: "drsatanic/drsatanic.github.io"
logo: "assets/images/logo.jpg"

twitter_username: ""
github_username: "drsatanic"

remote_theme: "mmistakes/minimal-mistakes@master"
minimal_mistakes_skin: "dirt"
search: true

markdown: kramdown
highlighter: rough
paginate: 5
paginate_path: "/page/:num/"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: "as_char"
  toc_levels: 1..6
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"
  enable_coderay: false

sass:
  sass_dir: "_sass"
  style: "compressed"
  
pagination:
  enabled: true
    debug: false
  collection: "posts"
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
  category: "posts"
  tag: ""
  locale: ""
  trail:
    before: 2
    after: 2
timezone: "Europe/London"

include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - Rakefike
  - README
  
keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
  
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Doctor Samael"
  avatar : "assets/images/avatar.png"
  bio    : "Did you really seen the Title?"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://drsatanic.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/drsatanic"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mstdn.plus/@luciferous"

footer:
  links:
    - label: "Email"
      icon: "fab fa-fw fa-envelope-square"
      url: "mailto:drsamael@zohomail.cn"
    - label: "Bear"
      icon: "fab fa-fw fa-link"
      url: "https://drsamael.bearblog.dev/"
    - label: "Blogger"
      icon: "fab fa-fw fa-blog"
      url: "https://drsamael.blogspot.com/"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
